# Config Schema for Firebase.

firebase.configuration:
  type: config_object
  label: 'Firebase settings'
  mapping:
    firebase_server_key:
      type: string
      label: 'Firebase server key'
    firebase_endpoint:
      type: string
      label: 'Firebase endpoint'
